package terceros;


/**
* terceros/tercero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from terceros.idl
* jueves 27 de septiembre de 2018 02H13' COT
*/

public interface tercero extends terceroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface tercero
