package terceros;


/**
* terceros/terceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from terceros.idl
* jueves 27 de septiembre de 2018 02H13' COT
*/

public interface terceroOperations 
{
  boolean insertartercero (String nombres, String apellidos, int telefono);
  boolean actualizartercero (int id, String nombres, String apellidos, int telefono);
  boolean eliminartercero (int id);
  String consultartercero (int id);
  void shoutdown ();
} // interface terceroOperations
